# Generated by Django 4.1.6 on 2023-02-10 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=3, verbose_name='Серия (3 цифры)')),
                ('number', models.CharField(max_length=8, verbose_name='Номер (8 цифр)')),
                ('date1', models.DateTimeField(verbose_name='Дата выпуска')),
                ('date2', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('last_use', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего использования')),
                ('total_sum', models.FloatField(default=0, verbose_name='Сумма покупок')),
                ('status', models.IntegerField(choices=[(0, 'Не активирована'), (1, 'Активирована'), (2, 'Просрочена'), (3, 'В корзине')], default=0, verbose_name='Статус')),
                ('discount', models.FloatField(default=1, verbose_name='Текущая скидка')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6, verbose_name='Номер')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('order_sum', models.FloatField(default=0, verbose_name='Сумма')),
                ('discount', models.FloatField(default=0, verbose_name='Процент скидки')),
                ('discount_sum', models.FloatField(default=0, verbose_name='Сумма скидки')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='loyalty_management.card', verbose_name='Карта')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('discount_price', models.FloatField(default=0, verbose_name='Цена со скидкой')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='loyalty_management.order', verbose_name='Заказ')),
            ],
        ),
    ]
